<?php
namespace console\controllers;
use Yii;
use yii\console\Controller;

/**
 * Manipular la tabla partida_generica
 */
class PartidaSubEspecificaController extends Controller
{
	/**
	 * Cargar la lista de partidas genéricas a la BD
	 */
	public function actionCargar()
	{
		echo "Insertando registros...\n";
		
		$resultado = Yii::$app->db->createCommand('INSERT INTO partida_especifica (cuenta,partida,generica,especifica,nombre,estatus) VALUES
			("3","01","01","01","Impuesto sobre la renta a personas jurídicas",1),
			("3","01","01","02","Impuesto sobre la renta a personas naturales",1),
			("3","01","01","03","Impuestos sobre sucesiones, donaciones y demás ramos conexos",1),
			("3","01","01","04","Reparos administrativos por impuesto sobre la renta a personas juridica",1),
			("3","01","01","05","Reparos administrativos por impuesto sobre la renta a personas naturales",1),
			("3","01","01","06","Reparos administrativos a impuesto sobre sucesiones, donaciones y demás ramos conexos",1),
			("3","01","02","01","Impuestos de importación",1),
			("3","01","02","02","Impuesto de exportación",1),
			("3","01","02","03","Impuesto sobre la producción, el consumo y transacciones financieras",1),
			("3","01","02","04","Impuestos a las actividades de juegos de envite o azar",1),
			("3","01","02","05","Inmuebles urbanos",1),
			("3","01","02","06","Participación en el impuesto a la propiedad rural",1),
			("3","01","02","07","Patente de industria y comercio",1),
			("3","01","02","08","Patente de vehículo",1),
			("3","01","02","09","Propaganda comercial",1),
			("3","01","02","10","Espectáculos públicos",1),
			("3","01","02","11","Apuestas lícitas",1),
			("3","01","02","12","Deudas morosas",1),
			("3","01","02","99","Otros impuestos indirectos",1),
			("3","01","03","01","Derechos de tránsito terrestre",1),
			("3","01","03","02","Derechos a examen",1),
			("3","01","03","03","Derechos de expedición, renovación y reválida de licencias",1),
			("3","01","03","04","Derechos de registro y traspaso",1),
			("3","01","03","05","Derechos de placas identificadoras",1),
			("3","01","03","06","Derechos por revisión anual",1),
			("3","01","03","07","Derechos por remoción o arrastre de vehículos",1),
			("3","01","03","08","Derechos por estacionamiento de vehículos",1),
			("3","01","03","09","Permiso para uso de rutas extraurbanas",1),
			("3","01","03","10","Copias de documentos",1),
			("3","01","03","11","Tasas para el uso de aeronaves y por licencias de personal aeronáutico",1),
			("3","01","03","12","Tasas aeroportuarias",1),
			("3","01","03","13","Tasas por uso de canales de navegación",1),
			("3","01","03","14","Patente de navegación",1),
			("3","01","03","15","Expedición de licencias de navegación",1),
			("3","01","03","16","Servicio de telecomunicaciones",1),
			("3","01","03","17","Permisos para estaciones privadas de radiocomunicaciones",1),
			("3","01","03","18","Derechos de pilotajes",1),
			("3","01","03","19","Habilitación de pilotaje",1),
			("3","01","03","20","Servicios de remolcadores",1),
			("3","01","03","21","Habilitación de remolcadores",1),
			("3","01","03","22","Habilitación de capitanías de puerto",1),
			("3","01","03","23","Otros servicios de capitanías de puerto",1),
			("3","01","03","24","Tasas de faros y boyas",1),
			("3","01","03","25","Servicios de aduana",1),
			("3","01","03","26","Habilitación de aduanas",1),
			("3","01","03","27","Derechos de almacenaje",1),
			("3","01","03","28","Corretaje de bultos postales",1),
			("3","01","03","29","Servicios de consulta sobre clasificación arancelaria, valoración aduanera y análisis de laboratorio",1),
			("3","01","03","30","Bandas de garantía, cápsulas y sellos",1),
			("3","01","03","31","Servicio de peaje",1),
			("3","01","03","32","Servicio de riego y drenaje",1),
			("3","01","03","33","Estampillas fiscales",1),
			("3","01","03","34","Papel sellado",1),
			("3","01","03","35","Derechos de traslado",1),
			("3","01","03","36","Servicios sanitarios marítimos",1),
			("3","01","03","37","Servicios hospitalarios",1),
			("3","01","03","38","Venta de copias de planos",1),
			("3","01","03","39","Derechos de contraste, verificación y estudios",1),
			("3","01","03","40","Patente de pesca de perlas",1),
			("3","01","03","41","Licencia de caza",1),
			("3","01","03","42","Derechos de cancillería",1),
			("3","01","03","43","Depósitos por el ingreso al país de extranjeros",1),
			("3","01","03","44","Registro sanitario",1),
			("3","01","03","45","Derechos de análisis de sustancias químicas",1),
			("3","01","03","46","Derechos consulares",1),
			("3","01","03","47","Matrícula para importar y exportar sustancias estupefacientes y psicotrópicas",1),
			("3","01","03","48","Permisos municipales",1),
			("3","01","03","49","Certificaciones y solvencias",1),
			("3","01","03","50","Servicio de energía eléctrica",1),
			("3","01","03","51","Servicio de distribución de agua",1),
			("3","01","03","52","Servicio de gas doméstico",1),
			("3","01","03","53","Mensura y deslinde",1),
			("3","01","03","54","Aseo domiciliario",1),
			("3","01","03","55","Matadero",1),
			("3","01","03","56","Mercado",1),
			("3","01","03","57","Cementerio",1),
			("3","01","03","58","Terminal de pasajeros",1),
			("3","01","03","59","Deudas morosas por tasas",1),
			("3","01","03","99","Otros tipos de tasas",1),
			("3","01","04","01","Sobre la plusvalía inmobiliaria",1),
			("3","01","04","02","Contribuciones por mejoras",1),
			("3","01","04","99","Otras contribuciones especiales",1),
			("3","01","05","01","Ingresos por aportes patronales a la seguridad social",1),
			("3","01","05","02","Contribuciones personales a la seguridad social",1),
			("3","01","06","01","Regalías",1),
			("3","01","06","02","Impuesto superficial de hidrocarburos",1),
			("3","01","06","03","Impuesto de extracción",1),
			("3","01","06","04","Impuesto de registro de exportación",1),
			("3","01","06","05","Participación por azufre",1),
			("3","01","06","06","Participación por coque",1),
			("3","01","06","07","Ventajas especiales petroleras",1),
			("3","01","06","99","Otros ingresos del dominio petrolero",1),
			("3","01","07","01","Superficial minero",1),
			("3","01","07","02","Impuesto de explotación",1),
			("3","01","07","03","Ventajas especiales mineras",1),
			("3","01","07","04","Regalía minera de oro",1),
			("3","01","08","01","Impuesto superficial",1),
			("3","01","08","02","Impuesto de explotación o aprovechamiento",1),
			("3","01","08","03","Permiso o autorización para la explotación o aprovechamiento de los productos forestales",1),
			("3","01","08","04","Autorización para deforestación",1),
			("3","01","08","05","Autorización para movilizar productos forestales",1),
			("3","01","08","06","Participación por la explotación en zonas de reserva forestal",1),
			("3","01","08","07","Ventajas especiales por recursos forestales",1),
			("3","01","09","01","Ingresos por la venta de bienes",1),
			("3","01","09","02","Ingresos por la venta de servicios",1),
			("3","01","09","99","Ingresos por la venta de otros bienes y servicios",1),
			("3","01","10","01","Intereses por préstamos concedidos al sector privado",1),
			("3","01","10","03","Intereses por préstamos concedidos al sector externo",1),
			("3","01","10","04","Intereses por depósitos en instituciones financieras",1),
			("3","01","10","05","Intereses de títulos y valores",1),
			("3","01","10","06","Utilidades de acciones y participaciones de capital",1),
			("3","01","10","07","Utilidades de explotación de juegos de azar",1),
			("3","01","10","08","Alquileres",1),
			("3","01","10","09","Derechos sobre bienes intangibles",1),
			("3","01","10","10","Concesiones de bienes y servicios",1),
			("3","01","11","01","Intereses moratorios",1),
			("3","01","11","02","Reparos fiscales",1),
			("3","01","11","03","Sanciones fiscales",1),
			("3","01","11","04","Juicios y costas procesales",1),
			("3","01","11","05","Beneficios en operaciones cambiarias",1),
			("3","01","11","06","Utilidad por venta de activos",1),
			("3","01","11","07","Intereses por financiamiento de deudas tributarias",1),
			("3","01","11","08","Multas y recargos",1),
			("3","01","11","09","Reparos administrativos al impuesto a los activos empresariales",1),
			("3","01","11","10","Diversos reparos administrativos",1),
			("3","01","11","11","Ingresos en tránsito",1),
			("3","01","11","12","Reparos administrativos por impuestos municipales",1),
			("3","01","99","01","Otros ingresos ordinarios",1),
			("3","02","01","01","Colocación de títulos y valores de deuda pública interna a corto plazo",1),
			("3","02","01","02","Obtención de préstamos internos a corto plazo",1),
			("3","02","01","03","Colocación de títulos y valores de la deuda pública interna a largo plazo",1),
			("3","02","01","04","Obtención de préstamos internos a largo plazo",1),
			("3","02","02","01","Colocación de títulos y valores de la deuda pública externa a corto plazo",1),
			("3","02","02","02","Obtención de préstamos externos a corto plazo",1),
			("3","02","02","03","Colocación de títulos y valores de la deuda pública externa a largo plazo",1),
			("3","02","02","04","Obtención de préstamos externos a largo plazo",1),
			("3","02","03","01","Liquidación de entes descentralizados",1),
			("3","02","03","02","Herencias vacantes y donaciones",1),
			("3","02","03","03","Prima en colocación de títulos y valores de la deuda pública",1),
			("3","02","03","05","Ingresos por procesos licitatorios",1),
			("3","02","04","01","Reintegro proveniente de bonos de exportación",1),
			("3","02","04","02","Reintegro de fondos efectuado por organismos públicos proveniente de bonos de exportación",1),
			("3","02","05","01","Ingresos por obtención indebida de devoluciones o reintegros",1),
			("3","02","06","01","Impuesto a las transacciones financieras",1),
			("3","02","06","02","Reparos administrativos al impuesto a las transacciones financieras",1),
			("3","02","06","03","Multas y recargos por el impuesto a las transacciones financieras",1),
			("3","02","99","01","Otros ingresos extraordinarios",1),
			("3","03","01","01","Venta de productos del sector industrial",1),
			("3","03","01","02","Venta de productos del sector comercial",1),
			("3","03","02","01","Venta bruta de servicios",1),
			("3","03","03","01","Ingresos por inversiones en valores",1),
			("3","03","03","02","Ingresos por cartera de créditos",1),
			("3","03","03","03","Ingresos provenientes de la administración de fideicomisos",1),
			("3","03","03","99","Otros ingresos financieros",1),
			("3","03","04","01","Ingresos por inversiones en valores",1),
			("3","03","04","02","Ingresos por cartera de créditos",1),
			("3","03","04","03","Ingresos provenientes de la administración de fideicomisos",1),
			("3","03","04","99","Otros ingresos financieros",1),
			("3","03","05","01","Ingresos por operaciones de primas de seguro",1),
			("3","03","05","02","Ingresos por operaciones de reaseguro",1),
			("3","03","05","03","Ingresos por salvamento de siniestros",1),
			("3","03","05","99","Otros ingresos por operaciones de seguro",1),
			("3","03","99","01","Otros ingresos de operación",1),
			("3","04","01","01","Subsidios para precios y tarifas",1),
			("3","04","02","01","Incentivos a la exportación",1),
			("3","04","99","01","Otros ingresos ajenos a la operación",1),
			("3","05","01","01","Transferencias corrientes internas del sector privado",1),
			("3","05","01","02","Donaciones corrientes internas del sector privado",1),
			("3","05","01","03","Transferencias corrientes internas del sector público",1),
			("3","05","01","04","Donaciones corrientes internas del sector público",1),
			("3","05","01","05","Transferencias corrientes del exterior",1),
			("3","05","01","06","Donaciones corrientes del exterior",1),
			("3","05","02","01","Transferencias de capital internas del sector privado",1),
			("3","05","02","02","Donaciones de capital internas del sector privado",1),
			("3","05","02","03","Transferencias de capital internas del sector público",1),
			("3","05","02","04","Donaciones de capital internas del sector público",1),
			("3","05","02","05","Transferencias de capital del exterior",1),
			("3","05","02","06","Donaciones de capital del exterior",1),
			("3","05","03","01","Situado Constitucional",1),
			("3","05","03","02","Situado Estadal a Municipal",1),
			("3","05","04","01","Subsidio de Régimen Especial",1),
			("3","05","05","01","Subsidio de Capitalidad",1),
			("3","05","06","01","Asignaciones Económicas Especiales (LAEE) Estadal",1),
			("3","05","06","02","Asignaciones Económicas Especiales (LAEE) Estadal a Municipal",1),
			("3","05","06","03","Asignaciones Económicas Especiales (LAEE) Municipal",1),
			("3","05","06","04","Asignaciones Económicas Especiales (LAEE) Fondo Nacional de los Consejos Comunales",1),
			("3","05","06","05","Asignaciones Económicas Especiales (LAEE) Apoyo al Fortalecimiento Institucional",1),
			("3","05","07","01","Fondo Intergubernamental para la Descentralización (FIDES)",1),
			("3","05","08","01","Fondo de Compensación Interterritorial Estadal",1),
			("3","05","08","02","Fondo de Compensación Interterritorial Municipal",1),
			("3","05","08","03","Fondo de Compensación Interterritorial Poder Popular",1),
			("3","05","08","04","Fondo de Compensación Interterritorial Fortalecimiento Institucional",1),
			("3","05","09","01","Aportes del Sector Público al Poder Estadal por transferencia de servicios",1),
			("3","05","09","02","Aportes del Sector Público al Poder Municipal por transferencia de servicios",1),
			("3","05","10","01","Transferencias y donaciones corrientes de Organismos del Sector Público a los Consejos Comunales",1),
			("3","05","10","02","Transferencias y donaciones de capital de Organismos del Sector Público a los Consejos Comunales",1),
			("3","06","01","01","Venta y/o desincorporación de tierras y terrenos",1),
			("3","06","01","02","Venta y/o desincorporación de edificios e instalaciones",1),
			("3","06","01","03","Venta y/o desincorporación de maquinarias, equipos y semovientes",1),
			("3","06","02","01","Venta de marcas de fábrica y patentes de invención",1),
			("3","06","02","02","Venta de derechos de autor",1),
			("3","06","02","03","Recuperación de gastos de organización",1),
			("3","06","02","04","Venta de paquetes y programas de computación",1),
			("3","06","02","05","Venta de estudios y proyectos",1),
			("3","06","02","99","Venta de otros activos intangibles",1),
			("3","06","03","01","Incremento de la depreciación acumulada",1),
			("3","06","03","02","Incremento de la amortización acumulada",1),
			("3","07","01","01","Venta de títulos y valores privados de corto plazo",1),
			("3","07","01","02","Venta de títulos y valores públicos de corto plazo",1),
			("3","07","01","03","Venta de títulos y valores externos de corto plazo",1),
			("3","07","02","01","Venta de títulos y valores privados de largo plazo",1),
			("3","07","02","02","Venta de títulos y valores públicos de largo plazo",1),
			("3","07","02","03","Venta de títulos y valores externos de largo plazo",1),
			("3","08","01","01","Venta de acciones y participaciones de capital del sector privado",1),
			("3","08","02","01","Venta de acciones y participaciones de capital de entes descentralizados sin fines empresariales",1),
			("3","08","02","02","Venta de acciones y participaciones de capital de instituciones de protección social",1),
			("3","08","02","03","Venta de acciones y participaciones de capital de entes descentralizados con fines empresariales petroleros",1),
			("3","08","02","04","Venta de acciones y participaciones de capital de entes descentralizados con fines empresariales no petroleros",1),
			("3","08","02","05","Venta de acciones y participaciones de capital de entes descentralizados financieros bancarios",1),
			("3","08","02","06","Venta de acciones y participaciones de capital de entes descentralizados financieros no bancarios",1),
			("3","08","03","01","Venta de acciones y participaciones de capital de organismos internacionales",1),
			("3","08","03","99","Venta de acciones y participaciones de capital de otros entes del sector externo",1),
			("3","09","01","01","Recuperación de préstamos otorgados al sector privado de corto plazo",1),
			("3","09","02","01","Recuperación de préstamos otorgados a la República de corto plazo",1),
			("3","09","02","02","Recuperación de préstamos otorgados a entes descentralizados sin fines empresariales de corto plazo",1),
			("3","09","02","03","Recuperación de préstamos otorgados a instituciones de protección social de corto plazo",1),
			("3","09","02","04","Recuperación de préstamos otorgados a entes descentralizados con fines empresariales petroleros de corto plazo",1),
			("3","09","02","05","Recuperación de préstamos otorgados a entes descentralizados con fines empresariales no petroleros de corto plazo",1),
			("3","09","02","06","Recuperación de préstamos otorgados a entes descentralizados financieros bancarios de corto plazo",1),
			("3","09","02","07","Recuperación de préstamos otorgados a entes descentralizados financieros no bancarios de corto plazo",1),
			("3","09","02","08","Recuperación de préstamos otorgados al Poder Estadal de corto plazo",1),
			("3","09","02","09","Recuperación de préstamos otorgados al Poder Municipal de corto plazo",1),
			("3","09","03","01","Recuperación de préstamos otorgados a instituciones sin fines de lucro de corto plazo",1),
			("3","09","03","02","Recuperación de préstamos otorgados a gobiernos extranjeros de corto plazo",1),
			("3","09","03","03","Recuperación de préstamos otorgados a los organismos internacionales de corto plazo",1),
			("3","10","01","01","Recuperación de préstamos otorgados al sector privado de largo plazo",1),
			("3","10","02","01","Recuperación de préstamos otorgados a la República de largo plazo",1),
			("3","10","02","02","Recuperación de préstamos otorgados a entes descentralizados sin fines empresariales de largo plazo",1),
			("3","10","02","03","Recuperación de préstamos otorgados a instituciones de protección social de largo plazo",1),
			("3","10","02","04","Recuperación de préstamos otorgados a entes descentralizados con fines empresariales petroleros de largo plazo",1),
			("3","10","02","05","Recuperación de préstamos otorgados a entes descentralizados con fines empresariales no petroleros de largo plazo",1),
			("3","10","02","06","Recuperación de préstamos otorgados a entes descentralizados financieros bancarios de largo plazo",1),
			("3","10","02","07","Recuperación de préstamos otorgados a entes descentralizados financieros no bancarios de largo plazo",1),
			("3","10","02","08","Recuperación de préstamos otorgados al Poder Estadal de largo plazo",1),
			("3","10","02","09","Recuperación de préstamos otorgados al Poder Municipal de largo plazo",1),
			("3","10","03","01","Recuperación de préstamos otorgados a instituciones sin fines de lucro de largo plazo",1),
			("3","10","03","02","Recuperación de préstamos otorgados a gobiernos extranjeros de largo plazo",1),
			("3","10","03","03","Recuperación de préstamos otorgados a organismos internacionales de largo plazo",1),
			("3","11","01","01","Disminución de caja",1),
			("3","11","01","02","Disminución de bancos",1),
			("3","11","01","03","Disminución de inversiones temporales",1),
			("3","11","02","01","Disminución de cuentas comerciales por cobrar a corto plazo",1),
			("3","11","02","02","Disminución de rentas por recaudar a corto plazo",1),
			("3","11","02","03","Disminución de deudas de cuentas por rendir a corto plazo",1),
			("3","11","02","99","Disminución de otras cuentas por cobrar a corto plazo",1),
			("3","11","03","01","Disminución de efectos comerciales por cobrar a corto plazo",1),
			("3","11","03","99","Disminución de otros efectos por cobrar a corto plazo",1),
			("3","11","04","01","Disminución de cuentas comerciales por cobrar a mediano y largo plazo",1),
			("3","11","04","02","Disminución de rentas por recaudar a mediano y largo plazo",1),
			("3","11","04","99","Disminución de otras cuentas por cobrar a mediano y largo plazo",1),
			("3","11","05","01","Disminución de efectos comerciales por cobrar a mediano y largo plazo",1),
			("3","11","05","99","Disminución de otros efectos por cobrar a mediano y largo plazo",1),
			("3","11","06","01","Disminución de fondos en avance",1),
			("3","11","06","02","Disminución de fondos en anticipo",1),
			("3","11","06","03","Disminución de fondos en fideicomiso",1),
			("3","11","06","04","Disminución de anticipos a proveedores",1),
			("3","11","06","05","Disminución de anticipos a contratistas, por contratos a corto plazo",1),
			("3","11","06","06","Disminución de anticipos a contratistas, por contratos a mediano y largo plazo",1),
			("3","11","07","01","Disminución de gastos a corto plazo pagados por anticipado",1),
			("3","11","07","02","Disminución de depósitos en garantía a corto plazo",1),
			("3","11","07","99","Disminución de otros activos diferidos a corto plazo",1),
			("3","11","08","01","Disminución de gastos a mediano y largo plazo pagados por anticipado",1),
			("3","11","08","02","Disminución de depósitos en garantía a mediano y largo plazo",1),
			("3","11","08","99","Disminución de otros activos diferidos a mediano y largo plazo",1),
			("3","11","09","01","Disminución del Fondo de Estabilización Macroeconómica (FEM) de la República",1),
			("3","11","09","02","Disminución del Fondo de Estabilización Macroeconómica (FEM) del Poder Estadal",1),
			("3","11","09","03","Disminución del Fondo de Estabilización Macroeconómica (FEM) del Poder Municipal",1),
			("3","11","10","01","Disminución del Fondo de Ahorro Intergeneracional",1),
			("3","11","12","01","Disminución del Fondo de Aporte del Sector Público",1),
			("3","11","20","01","Disminución de activos financieros en gestión judicial a mediano y largo plazo",1),
			("3","11","20","02","Disminución de títulos y otros valores de la deuda pública en litigio a largo plazo",1),
			("3","11","99","01","Disminución de otros activos financieros circulantes",1),
			("3","11","99","02","Disminución de otros activos financieros no circulantes",1),
			("3","12","01","01","Incremento de sueldos, salarios y otras remuneraciones por pagar",1),
			("3","12","02","01","Incremento de aportes patronales y retenciones laborales por pagar al Instituto Venezolano de los Seguros Sociales (IVSS)",1),
			("3","12","02","02","Incremento de aportes patronales y retenciones laborales por pagar al Instituto de Previsión Social del Ministerio de Educación (Ipasme)",1),
			("3","12","02","03","Incremento de aportes patronales y retenciones laborales por pagar al Fondo de Jubilaciones",1),
			("3","12","02","04","Incremento de aportes patronales y retenciones laborales por pagar al Fondo de Seguro de Paro Forzoso",1),
			("3","12","02","05","Incremento de aportes patronales y retenciones laborales por pagar al Fondo de Ahorro Obligatorio para la Vivienda (FAOV)",1),
			("3","12","02","06","Incremento de aportes patronales y retenciones laborales por pagar por seguro de vida, accidentes personales, hospitalización, cirugía y maternidad (HCM) y gastos funerarios",1),
			("3","12","02","07","Incremento de aportes patronales y retenciones laborales por pagar a cajas de ahorro",1),
			("3","12","02","08","Incremento de aportes patronales y retenciones laborales por pagar a los organismos de seguridad social",1),
			("3","12","02","09","Incremento de aportes patronales y retenciones laborales por pagar al Instituto Nacional de Capacitación y Educación Socialista (Inces)",1),
			("3","12","02","10","Incremento de aportes patronales y retenciones laborales por pagar por pensión alimenticia",1),
			("3","12","02","99","Incremento de otros aportes patronales y otras retenciones laborales por pagar",1),
			("3","12","03","01","Incremento de cuentas por pagar a proveedores a corto plazo",1),
			("3","12","03","02","Incremento de efectos por pagar a proveedores a corto plazo",1),
			("3","12","03","03","Incremento de cuentas por pagar a proveedores a mediano y largo plazo",1),
			("3","12","03","04","Incremento de efectos por pagar a proveedores a mediano y largo plazo",1),
			("3","12","04","01","Incremento de cuentas por pagar a contratistas a corto plazo",1),
			("3","12","04","02","Incremento de efectos por pagar a contratistas a corto plazo",1),
			("3","12","04","03","Incremento de cuentas por pagar a contratistas a mediano y largo plazo",1),
			("3","12","04","04","Incremento de efectos por pagar a contratistas a mediano y largo plazo",1),
			("3","12","05","01","Incremento de intereses internos por pagar",1),
			("3","12","05","02","Incremento de intereses externos por pagar",1),
			("3","12","06","01","Incremento de otras cuentas por pagar a corto plazo",1),
			("3","12","06","02","Incremento de otras obligaciones de ejercicios anteriores por pagar",1),
			("3","12","06","03","Incremento de otros efectos por pagar a corto plazo",1),
			("3","12","07","01","Incremento de pasivos diferidos a corto plazo",1),
			("3","12","07","02","Incremento de pasivos diferidos a mediano y largo plazo",1),
			("3","12","08","01","Incremento de provisiones",1),
			("3","12","08","02","Incremento de reservas técnicas",1),
			("3","12","09","01","Incremento de depósitos recibidos en garantía",1),
			("3","12","09","99","Incremento de otros fondos de terceros",1),
			("3","12","10","01","Incremento de depósitos a la vista",1),
			("3","12","10","02","Incremento de depósitos a plazo fijo",1),
			("3","12","11","01","Incremento por reestructuración y/o refinanciamiento de la deuda pública interna de largo plazo en corto plazo",1),
			("3","12","11","02","Incremento por reestructuración y/o refinanciamiento de la deuda pública interna de corto plazo en largo plazo",1),
			("3","12","11","03","Incremento por reestructuración y/o refinanciamiento de la deuda pública externa de largo plazo en corto plazo",1),
			("3","12","11","04","Incremento por reestructuración y/o refinanciamiento de la deuda pública externa de corto plazo en largo plazo",1),
			("3","12","11","05","Incremento de la deuda pública por distribuir",1),
			("3","12","99","01","Incremento de otros pasivos a corto plazo",1),
			("3","12","99","02","Incremento de otros pasivos a mediano y largo plazo",1),
			("3","13","01","01","Incremento del capital fiscal e institucional",1),
			("3","13","01","02","Incremento de aportes por capitalizar",1),
			("3","13","01","03","Incremento de dividendos a distribuir",1),
			("3","13","02","01","Incremento de reservas",1),
			("3","13","03","01","Ajustes por inflación",1),
			("3","13","04","01","Incremento de resultados acumulados",1),
			("3","13","04","02","Incremento de resultados del ejercicio",1),
			("4","01","01","01","Sueldos básicos personal fijo a tiempo completo",1),
			("4","01","01","02","Sueldos básicos personal fijo a tiempo parcial",1),
			("4","01","01","03","Suplencias a empleados",1),
			("4","01","01","08","Sueldo al personal en trámite de nombramiento",1),
			("4","01","01","09","Remuneraciones al personal en período de disponibilidad",1),
			("4","01","01","10","Salarios a obreros en puestos permanentes a tiempo completo",1),
			("4","01","01","11","Salarios a obreros en puestos permanentes a tiempo parcial",1),
			("4","01","01","12","Salarios a obreros en puestos no permanentes",1),
			("4","01","01","13","Suplencias a obreros",1),
			("4","01","01","18","Remuneraciones al personal contratado",1),
			("4","01","01","19","Retribuciones por becas - salarios, bolsas de trabajo, pasantías y similares",1),
			("4","01","01","20","Sueldo del personal militar profesional",1),
			("4","01","01","21","Sueldo o ración del personal militar no profesional",1),
			("4","01","01","22","Sueldo del personal militar de reserva",1),
			("4","01","01","29","Dietas",1),
			("4","01","01","30","Retribución al personal de reserva",1),
			("4","01","01","35","Sueldo básico de los altos funcionarios y altas funcionarias del poder público y de elección popular",1),
			("4","01","01","36","Sueldo básico del personal de alto nivel y de dirección",1),
			("4","01","01","37","Dietas de los altos funcionarios y altas funcionarias del poder público y de elección popular",1),
			("4","01","01","38","Dietas del personal de alto nivel y de dirección",1),
			("4","01","01","99","Otras retribuciones",1),
			("4","01","02","01","Compensaciones previstas en las escalas de sueldos al personal empleado fijo a tiempo completo",1),
			("4","01","02","02","Compensaciones previstas en las escalas de sueldos al personal empleado fijo a tiempo parcial",1),
			("4","01","02","03","Compensaciones previstas en las escalas de salarios al personal obrero fijo a tiempo completo",1),
			("4","01","02","04","Compensaciones previstas en las escalas de salarios al personal obrero fijo a tiempo parcial",1),
			("4","01","02","05","Compensaciones previstas en las escalas de sueldos al personal militar",1),
			("4","01","02","06","Compensaciones previstas en las escalas de sueldos de los altos funcionarios y altas funcionarias del poder público y de elección popular",1),
			("4","01","02","07","Compensaciones previstas en las escalas de sueldos del personal de alto nivel y de dirección",1),
			("4","01","03","01","Primas por mérito a empleados",1),
			("4","01","03","02","Primas de transporte a empleados",1),
			("4","01","03","03","Primas por hogar a empleados",1),
			("4","01","03","04","Primas por hijos a empleados",1),
			("4","01","03","05","Primas por alquileres a empleados",1),
			("4","01","03","06","Primas por residencia a empleados",1),
			("4","01","03","07","Primas por categoría de escuelas a empleados",1),
			("4","01","03","08","Primas de profesionalización a empleados",1),
			("4","01","03","09","Primas por antigüedad a empleados",1),
			("4","01","03","10","Primas por jerarquía o responsabilidad en el cargo",1),
			("4","01","03","11","Primas al personal en servicio en el exterior",1),
			("4","01","03","16","Primas por mérito a obreros",1),
			("4","01","03","17","Primas de transporte a obreros",1),
			("4","01","03","18","Primas por hogar a obreros",1),
			("4","01","03","19","Primas por hijos de obreros",1),
			("4","01","03","20","Primas por residencia a obreros",1),
			("4","01","03","21","Primas por antigüedad a obreros",1),
			("4","01","03","22","Primas de profesionalización a obreros",1),
			("4","01","03","26","Primas por hijos al personal militar",1),
			("4","01","03","27","Primas de profesionalización al personal militar",1),
			("4","01","03","28","Primas por antigüedad al personal militar",1),
			("4","01","03","29","Primas por potencial de ascenso al personal militar",1),
			("4","01","03","30","Primas por frontera y sitios inhóspitos al personal militar y de seguridad",1),
			("4","01","03","31","Primas por riesgo al personal militar y de seguridad",1),
			("4","01","03","37","Primas de transporte al personal contratado",1),
			("4","01","03","38","Primas por hogar al personal contratado",1),
			("4","01","03","39","Primas por hijos al personal contratado",1),
			("4","01","03","40","Primas de profesionalización al personal contratado",1),
			("4","01","03","41","Primas por antigüedad al personal contratado",1),
			("4","01","03","46","Primas a los altos funcionarios y altas funcionarias del poder público y de elección popular",1),
			("4","01","03","47","Primas al personal de alto nivel y de dirección",1),
			("4","01","03","94","Otras primas a los altos funcionarios y altas funcionarias del poder público y de elección popular",1),
			("4","01","03","95","Otras primas al personal de alto nivel y de dirección",1),
			("4","01","03","96","Otras primas al personal contratado",1),
			("4","01","03","97","Otras primas a empleados",1),
			("4","01","03","98","Otras primas a obreros",1),
			("4","01","03","99","Otras primas al personal militar",1),
			("4","01","04","01","Complemento a empleados por horas extraordinarias o por sobre tiempo",1),
			("4","01","04","02","Complemento a empleados por trabajo nocturno",1),
			("4","01","04","03","Complemento a empleados por gastos de alimentación",1),
			("4","01","04","04","Complemento a empleados por gastos de transporte",1),
			("4","01","04","05","Complemento a empleados por gastos de representación",1),
			("4","01","04","06","Complemento a empleados por comisión de servicios",1),
			("4","01","04","07","Bonificación a empleados",1),
			("4","01","04","08","Bono compensatorio de alimentación a empleados",1),
			("4","01","04","09","Bono compensatorio de transporte a empleados",1),
			("4","01","04","10","Complemento a empleados por días feriados",1),
			("4","01","04","14","Complemento a obreros por horas extraordinarias o por sobre tiempo",1),
			("4","01","04","15","Complemento a obreros por trabajo o jornada nocturna",1),
			("4","01","04","16","Complemento a obreros por gastos de alimentación",1),
			("4","01","04","17","Complemento a obreros por gastos de transporte",1),
			("4","01","04","18","Bono compensatorio de alimentación a obreros",1),
			("4","01","04","19","Bono compensatorio de transporte a obreros",1),
			("4","01","04","20","Complemento a obreros por días feriados",1),
			("4","01","04","24","Complemento al personal contratado por horas extraordinarias o por sobre tiempo",1),
			("4","01","04","25","Complemento al personal contratado por gastos de alimentación",1),
			("4","01","04","26","Bono compensatorio de alimentación al personal contratado",1),
			("4","01","04","27","Bono compensatorio de transporte al personal contratado",1),
			("4","01","04","28","Complemento al personal contratado por días feriados",1),
			("4","01","04","32","Complemento al personal militar por gastos de alimentación",1),
			("4","01","04","33","Complemento al personal militar por gastos de transporte",1),
			("4","01","04","34","Complemento al personal militar en el exterior",1),
			("4","01","04","35","Bono compensatorio de alimentación al personal militar",1),
			("4","01","04","43","Complemento a altos funcionarios y altas funcionarias del poder público y de elección popular por gastos de representación",1),
			("4","01","04","44","Complemento a altos funcionarios y altas funcionarias del poder público y  de elección popular por comisión de servicios",1),
			("4","01","04","45","Bonificación a altos funcionarios y altas funcionarias del poder público y de elección popular",1),
			("4","01","04","46","Bono compensatorio de alimentación a altos funcionarios y altas funcionarias del poder público y de elección popular",1),
			("4","01","04","47","Bono compensatorio de transporte a altos funcionarios y altas funcionarias del poder público y de elección popular",1),
			("4","01","04","48","Complemento al personal de alto nivel y de dirección por gastos de representación",1),
			("4","01","04","49","Complemento al personal de alto nivel y de dirección por comisión de servicios",1),
			("4","01","04","50","Bonificación al personal de alto nivel y de dirección",1),
			("4","01","04","51","Bono compensatorio de alimentación al personal de alto nivel y de dirección",1),
			("4","01","04","52","Bono compensatorio de transporte al personal de alto nivel y de dirección",1),
			("4","01","04","94","Otros complementos a altos funcionarios y altas funcionarias del sector público y de elección popular",1),
			("4","01","04","95","Otros complementos al personal de alto nivel y de dirección",1),
			("4","01","04","96","Otros complementos a empleados",1),
			("4","01","04","97","Otros complementos a obreros",1),
			("4","01","04","98","Otros complementos al personal contratado",1),
			("4","01","04","99","Otros complementos al personal militar",1),
			("4","01","05","01","Aguinaldos a empleados",1),
			("4","01","05","02","Utilidades legales y convencionales a empleados",1),
			("4","01","05","03","Bono vacacional a empleados",1),
			("4","01","05","04","Aguinaldos a obreros",1),
			("4","01","05","05","Utilidades legales y convencionales a obreros",1),
			("4","01","05","06","Bono vacacional a obreros",1),
			("4","01","05","07","Aguinaldos al personal contratado",1),
			("4","01","05","08","Bono vacacional al personal contratado",1),
			("4","01","05","09","Aguinaldos al personal militar",1),
			("4","01","05","10","Bono vacacional al personal militar",1),
			("4","01","05","13","Aguinaldos a altos funcionarios y altas funcionarias del poder público y de elección popular",1),
			("4","01","05","14","Utilidades legales y convencionales a altos funcionarios y altas funcionarias del poder público y de elección popular",1),
			("4","01","05","15","Bono vacacional a altos funcionarios y altas funcionarias del poder público y de elección popular",1),
			("4","01","05","16","Aguinaldos al personal de alto nivel y de dirección",1),
			("4","01","05","17","Utilidades legales y convencionales al personal de alto nivel y de dirección",1),
			("4","01","05","18","Bono vacacional al personal de alto nivel y de dirección",1),
			("4","01","06","01","Aporte patronal al Instituto Venezolano de los Seguros Sociales (IVSS) por empleados",1),
			("4","01","06","02","Aporte patronal al Instituto de Previsión y Asistencia Social para el personal del Ministerio de Educación (Ipasme) por empleados",1),
			("4","01","06","03","Aporte patronal al Fondo de Jubilaciones por empleados",1),
			("4","01","06","04","Aporte patronal al Fondo de Seguro de Paro Forzoso por empleados",1),
			("4","01","06","05","Aporte patronal al Fondo de Ahorro Obligatorio para la Vivienda por empleados",1),
			("4","01","06","10","Aporte patronal al Instituto Venezolano de los Seguros Sociales (IVSS) por obreros",1),
			("4","01","06","11","Aporte patronal al Fondo de Jubilaciones por obreros",1),
			("4","01","06","12","Aporte patronal al Fondo de Seguro de Paro Forzoso por obreros",1),
			("4","01","06","13","Aporte patronal al Fondo de Ahorro Obligatorio para la Vivienda por obreros",1),
			("4","01","06","18","Aporte patronal a los organismos de seguridad social por los trabajadores locales empleados en las representaciones de Venezuela en el exterior",1),
			("4","01","06","19","Aporte patronal al Fondo de Ahorro Obligatorio para la Vivienda por personal militar",1),
			("4","01","06","25","Aporte legal al Instituto Venezolano de los Seguros Sociales (IVSS) por personal contratado",1),
			("4","01","06","26","Aporte patronal al Fondo de Ahorro Obligatorio para la Vivienda por personal contratado",1),
			("4","01","06","27","Aporte patronal al Fondo de Seguro de Paro Forzoso por personal contratado",1),
			("4","01","06","31","Aporte patronal al Instituto Venezolano de los Seguros Sociales (IVSS) por altos funcionarios y altas funcionarias del poder público y de elección popular",1),
			("4","01","06","32","Aporte patronal al Instituto de Previsión y Asistencia Social para el personal del Ministerio de Educación (Ipasme) por empleados personal del Ministerio de Educación (Ipasme) por altos funcionarios y altas funcionarias del poder público y de elección popular",1),
			("4","01","06","33","Aporte patronal al Fondo de Jubilaciones por altos funcionarios y altas funcionarias del poder público y de elección popular",1),
			("4","01","06","34","Aporte patronal al Fondo de Ahorro Obligatorio para la Vivienda por altos funcionarios y altas funcionarias del poder público y de elección popular",1),
			("4","01","06","35","Aporte patronal al Fondo de Seguro de Paro Forzoso por altos funcionarios y altas funcionarias del poder público y de elección popular",1),
			("4","01","06","39","Aporte patronal al Instituto Venezolano de los Seguros Sociales (IVSS) por personal de alto nivel y de dirección",1),
			("4","01","06","40","Aporte patronal al Instituto de Previsión y Asistencia Social para el personal del Ministerio de Educación (Ipasme) por personal de alto nivel y de dirección",1),
			("4","01","06","41","Aporte patronal al Fondo de Jubilaciones por personal de alto nivel y de dirección",1),
			("4","01","06","42","Aporte patronal al Fondo de Ahorro Obligatorio para la Vivienda por personal de alto nivel y de dirección",1),
			("4","01","06","43","Aporte patronal al Fondo de Seguro de Paro Forzoso por personal de alto nivel y de dirección",1),
			("4","01","06","93","Otros aportes legales por altos funcionarios y altas funcionarias del poder público y de elección popular",1),
			("4","01","06","94","Otros aportes legales por el personal de alto nivel y de dirección",1),
			("4","01","06","95","Otros aportes legales por personal contratado",1),
			("4","01","06","96","Otros aportes legales por empleados",1),
			("4","01","06","97","Otros aportes legales por obreros",1),
			("4","01","06","98","Otros aportes legales por personal militar",1),
			("4","01","07","01","Capacitación y adiestramiento a empleados",1),
			("4","01","07","02","Becas a empleados",1),
			("4","01","07","03","Ayudas por matrimonio a empleados",1),
			("4","01","07","04","Ayudas por nacimiento de hijos a empleados",1),
			("4","01","07","05","Ayudas por defunción a empleados",1),
			("4","01","07","06","Ayudas para medicinas, gastos médicos, odontológicos y de hospitalización a empleados",1),
			("4","01","07","07","Aporte patronal a cajas de ahorro por empleados",1),
			("4","01","07","08","Aporte patronal a los servicios de salud, accidentes personales y gastos funerarios por empleados",1),
			("4","01","07","09","Ayudas a empleados para adquisición de uniformes y útiles escolares de sus hijos",1),
			("4","01","07","10","Dotación de uniformes a empleados",1),
			("4","01","07","11","Aporte patronal para gastos de guarderías y preescolar para hijos de empleados",1),
			("4","01","07","12","Aportes para la adquisición de juguetes para los hijos del personal empleado",1),
			("4","01","07","17","Capacitación y adiestramiento a obreros",1),
			("4","01","07","18","Becas a obreros",1),
			("4","01","07","19","Ayudas por matrimonio de obreros",1),
			("4","01","07","20","Ayudas por nacimiento de hijos de obreros",1),
			("4","01","07","21","Ayudas por defunción a obreros",1),
			("4","01","07","22","Ayudas para medicinas, gastos médicos, odontológicos y de hospitalización a obreros",1),
			("4","01","07","23","Aporte patronal a cajas de ahorro por obreros",1),
			("4","01","07","24","Aporte patronal a los servicios de salud, accidentes personales y gastos funerarios por obreros",1),
			("4","01","07","25","Ayudas a obreros para adquisición de uniformes y útiles escolares de sus hijos",1),
			("4","01","07","26","Dotación de uniformes a obreros",1),
			("4","01","07","27","Aporte patronal para gastos de guarderías y preescolar para hijos de obreros",1),
			("4","01","07","28","Aportes para la adquisición de juguetes para los hijos del personal obrero",1),
			("4","01","07","34","Capacitación y adiestramiento al personal militar",1),
			("4","01","07","35","Becas al personal militar",1),
			("4","01","07","36","Ayudas por matrimonio al personal militar",1),
			("4","01","07","37","Ayudas por nacimiento de hijos al personal militar",1),
			("4","01","07","38","Ayudas por defunción al personal militar",1),
			("4","01","07","39","Ayudas para medicinas, gastos médicos, odontológicos y de hospitalización al personal militar",1),
			("4","01","07","40","Aporte patronal a caja de ahorro por personal militar",1),
			("4","01","07","41","Aporte patronal a los servicios de salud, accidentes personales y gastos funerarios personal militar",1),
			("4","01","07","42","Ayudas al personal militar para adquisición de uniformes y útiles escolares de sus hijos",1),
			("4","01","07","43","Aportes para la adquisición de juguetes para los hijos del personal militar",1),
			("4","01","07","44","Aporte patronal para gastos de guarderías y preescolar para hijos del personal militar",1),
			("4","01","07","52","Capacitación y adiestramiento a altos funcionarios y altas funcionarias del poder público y de elección popular",1),
			("4","01","07","53","Ayudas por matrimonio a altos funcionarios y altas funcionarias del poder público y de elección popular",1),
			("4","01","07","54","Ayudas por nacimiento de hijos altos funcionarios y altas funcionarias del poder público y de elección popular",1),
			("4","01","07","55","Ayudas por defunción a altos funcionarios y altas funcionarias del poder público y de elección popular",1),
			("4","01","07","56","Ayudas para medicinas, gastos médicos, odontológicos y de hospitalización a altos funcionarios y altas funcionarias del poder público y de elección popular",1),
			("4","01","07","57","Aporte patronal a cajas de ahorro por altos funcionarios y altas funcionarias del poder público y de elección popular",1),
			("4","01","07","58","Aporte patronal a los servicios de salud, accidentes personales y gastos funerarios por altos funcionarios y altas funcionarias del poder público y de elección popular",1),
			("4","01","07","63","Capacitación y adiestramiento al personal de alto nivel y de dirección",1),
			("4","01","07","64","Ayudas por matrimonio al personal de alto nivel y de dirección ",1),
			("4","01","07","65","Ayudas por nacimiento de hijos al personal de alto nivel y de dirección",1),
			("4","01","07","66","Ayudas por defunción al personal de alto nivel y de dirección",1),
			("4","01","07","67","Ayudas para medicinas, gastos médicos, odontológicos y de hospitalización al personal de alto nivel y de dirección",1),
			("4","01","07","68","Aporte patronal a cajas de ahorro por personal de alto nivel y de dirección",1),
			("4","01","07","69","Aporte patronal a los servicios de salud, accidentes personales y gastos funerarios por personal de alto nivel y de dirección",1),
			("4","01","07","74","Capacitación y adiestramiento al personal contratado",1),
			("4","01","07","75","Becas al personal contratado",1),
			("4","01","07","76","Ayudas por matrimonio al personal contratado",1),
			("4","01","07","77","Ayudas por nacimiento de hijos al personal contratado",1),
			("4","01","07","78","Ayudas por defunción al personal contratado",1),
			("4","01","07","79","Ayudas para medicinas, gastos médicos, odontológicos y de hospitalización al personal contratado",1),
			("4","01","07","80","Aporte patronal a cajas de ahorro por personal contratado",1),
			("4","01","07","81","Aporte patronal a los servicios de salud, accidentes personales y gastos funerarios por personal contratado",1),
			("4","01","07","82","Ayudas al personal contratado para adquisición de uniformes y útiles escolares de sus hijos",1),
			("4","01","07","83","Dotación de uniformes al personal contratado",1),
			("4","01","07","84","Aporte patronal para gastos de guarderías y preescolar para hijos del personal contratado",1),
			("4","01","07","85","Aportes para la adquisición de juguetes para los hijos del personal contratado",1),
			("4","01","07","94","Otras subvenciones a altos funcionarios y altas funcionarias del poder público y de elección popular",1),
			("4","01","07","95","Otras subvenciones al personal de alto nivel y de dirección",1),
			("4","01","07","96","Otras subvenciones a empleados",1),
			("4","01","07","97","Otras subvenciones a obreros",1),
			("4","01","07","98","Otras subvenciones al personal militar",1),
			("4","01","07","99","Otras subvenciones al personal contratado",1),
			("4","01","08","01","Prestaciones sociales e indemnizaciones a empleados",1),
			("4","01","08","02","Prestaciones sociales e indemnizaciones a obreros",1),
			("4","01","08","03","Prestaciones sociales e indemnizaciones al personal contratado",1),
			("4","01","08","04","Prestaciones sociales e indemnizaciones al personal militar",1),
			("4","01","08","06","Prestaciones sociales e indemnizaciones a altos funcionarios y altas funcionarias del poder público y de elección popular",1),
			("4","01","08","07","Prestaciones sociales e indemnizaciones al personal de alto nivel y Prestaciones sociales e indemnizaciones al personal de alto nivel y de dirección",1),
			("4","01","09","01","Capacitación y adiestramiento realizado por personal del organismo",1),
			("4","01","94","01","Otros gastos de los altos funcionarios y altas funcionarias del poder público y de elección popular",1),
			("4","01","95","01","Otros gastos del personal de alto nivel y de dirección",1),
			("4","01","96","01","Otros gastos del personal empleado",1),
			("4","01","97","01","Otros gastos del personal obrero",1),
			("4","01","98","01","Otros gastos del personal militar",1),
			("4","02","01","01","Alimentos y bebidas para personas",1),
			("4","02","01","02","Alimentos para animales",1),
			("4","02","01","03","Productos agrícolas y pecuarios",1),
			("4","02","01","04","Productos de la caza y pesca",1),
			("4","02","01","99","Otros productos alimenticios y agropecuarios",1),
			("4","02","02","01","Carbón mineral",1),
			("4","02","02","02","Petróleo crudo y gas natural",1),
			("4","02","02","03","Mineral de hierro",1),
			("4","02","02","04","Mineral no ferroso",1),
			("4","02","02","05","Piedra, arcilla, arena y tierra",1),
			("4","02","02","06","Mineral para la fabricación de productos químicos",1),
			("4","02","02","07","Sal para uso industrial",1),
			("4","02","02","99","Otros productos de minas, canteras y yacimientos",1),
			("4","02","03","01","Textiles",1),
			("4","02","03","02","Prendas de vestir",1),
			("4","02","03","03","Calzados",1),
			("4","02","03","99","Otros productos textiles y vestuarios",1),
			("4","02","04","01","Cueros y pieles",1),
			("4","02","04","02","Productos de cuero y sucedáneos del cuero",1),
			("4","02","04","03","Cauchos y tripas para vehículos",1),
			("4","02","04","99","Otros productos de cuero y caucho",1),
			("4","02","05","01","Pulpa de madera, papel y cartón",1),
			("4","02","05","02","Envases y cajas de papel y cartón",1),
			("4","02","05","03","Productos de papel y cartón para oficina",1),
			("4","02","05","04","Libros, revistas y periódicos",1),
			("4","02","05","05","Material de enseñanza",1),
			("4","02","05","06","Productos de papel y cartón para computación",1),
			("4","02","05","07","Productos de papel y cartón para la imprenta y reproducción",1),
			("4","02","05","99","Otros productos de pulpa, papel y cartón",1),
			("4","02","06","01","Sustancias químicas y de uso industrial",1),
			("4","02","06","02","Abonos, plaguicidas y otros",1),
			("4","02","06","03","Tintas, pinturas y colorantes",1),
			("4","02","06","04","Productos farmacéuticos y medicamentos",1),
			("4","02","06","05","Productos de tocador",1),
			("4","02","06","06","Combustibles y lubricantes",1),
			("4","02","06","07","Productos diversos derivados del petróleo y del carbón",1),
			("4","02","06","08","Productos plásticos",1),
			("4","02","06","09","Mezclas explosivas",1),
			("4","02","06","99","Otros productos de la industria química y conexos",1),
			("4","02","07","01","Productos de barro, loza y porcelana",1),
			("4","02","07","02","Vidrios y productos de vidrio",1),
			("4","02","07","03","Productos de arcilla para construcción",1),
			("4","02","07","04","Cemento, cal y yeso",1),
			("4","02","07","99","Otros productos minerales no metálicos",1),
			("4","02","08","01","Productos primarios de hierro y acero",1),
			("4","02","08","02","Productos de metales no ferrosos",1),
			("4","02","08","03","Herramientas menores, cuchillería y artículos generales de ferretería",1),
			("4","02","08","04","Productos metálicos estructurales",1),
			("4","02","08","05","Materiales de orden público, seguridad y defensa",1),
			("4","02","08","07","Material de señalamiento",1),
			("4","02","08","08","Material de educación",1),
			("4","02","08","09","Repuestos y accesorios para equipos de transporte",1),
			("4","02","08","10","Repuestos y accesorios para otros equipos",1),
			("4","02","08","99","Otros productos metálicos",1),
			("4","02","09","01","Productos primarios de madera",1),
			("4","02","09","02","Muebles y accesorios de madera para edificaciones",1),
			("4","02","09","99","Otros productos de madera",1),
			("4","02","10","01","Artículos de deporte, recreación y juguetes",1),
			("4","02","10","02","Materiales y útiles de limpieza y aseo",1),
			("4","02","10","03","Utensilios de cocina y comedor",1),
			("4","02","10","04","Útiles menores médico - quirúrgicos de laboratorio, dentales y de veterinaria",1),
			("4","02","10","05","Útiles de escritorio, oficina y materiales de instrucción",1),
			("4","02","10","06","Condecoraciones, ofrendas y similares",1),
			("4","02","10","07","Productos de seguridad en el trabajo",1),
			("4","02","10","08","Materiales para equipos de computación",1),
			("4","02","10","09","Especies timbradas y valores",1),
			("4","02","10","10","Útiles religiosos",1),
			("4","02","10","11","Materiales eléctricos",1),
			("4","02","10","12","Materiales para instalaciones sanitarias",1),
			("4","02","10","13","Materiales fotográficos",1),
			("4","02","10","99","Otros productos y útiles diversos",1),
			("4","02","11","01","Productos y artículos para la venta",1),
			("4","02","11","02","Maquinarias y equipos para la venta",1),
			("4","02","11","03","Inmuebles para la venta",1),
			("4","02","11","04","Tierras y terrenos para la venta",1),
			("4","02","11","99","Otros bienes para la venta",1),
			("4","02","99","01","Otros materiales y suministros",1),
			("4","03","01","01","Alquileres de edificios y locales",1),
			("4","03","01","02","Alquileres de edificios y locales",1),
			("4","03","01","03","Alquileres de tierras y terrenos",1),
			("4","03","02","01","Alquileres de maquinaria y demás equipos de construcción, campo, industria y taller",1),
			("4","03","02","02","Alquileres de equipos de transporte, tracción y elevación",1),
			("4","03","02","03","Alquileres de equipos de comunicaciones y de señalamiento",1),
			("4","03","02","04","Alquileres de equipos médico - quirúrgicos, dentales y de veterinaria",1),
			("4","03","02","05","Alquileres de equipos científicos, religiosos, de enseñanza y recreación",1),
			("4","03","02","06","Alquileres de máquinas, muebles y demás equipos de oficina y alojamiento",1),
			("4","03","02","99","Alquileres de otras maquinaria y equipos",1),
			("4","03","03","01","Marcas de fábrica y patentes de invención",1),
			("4","03","03","02","Derechos de autor",1),
			("4","03","03","03","Paquetes y programas de computación",1),
			("4","03","03","04","Concesión de bienes y servicios",1),
			("4","03","04","01","Electricidad",1),
			("4","03","04","02","Gas",1),
			("4","03","04","03","Agua",1),
			("4","03","04","04","Teléfonos",1),
			("4","03","04","05","Servicio de comunicaciones",1),
			("4","03","04","06","Servicio de aseo urbano y domiciliario",1),
			("4","03","04","07","Servicio de condominio",1),
			("4","03","05","01","Servicio de administración, vigilancia y mantenimiento del servicio de electricidad",1),
			("4","03","05","02","Servicio de administración, vigilancia y mantenimiento del servicio de gas",1),
			("4","03","05","03","Servicio de administración, vigilancia y mantenimiento del servicio de agua",1),
			("4","03","05","04","Servicio de administración, vigilancia y mantenimiento del servicio de teléfonos",1),
			("4","03","05","05","Servicio de administración, vigilancia y mantenimiento del servicio de comunicaciones",1),
			("4","03","05","06","Servicio de administración, vigilancia y mantenimiento del servicio de aseo urbano y domiciliario",1),
			("4","03","06","01","Fletes y embalajes",1),
			("4","03","06","02","Almacenaje",1),
			("4","03","06","03","Estacionamiento",1),
			("4","03","06","04","Peaje",1),
			("4","03","06","05","Servicios de protección en traslado de fondos y de mensajería",1),
			("4","03","07","01","Publicidad y propaganda",1),
			("4","03","07","02","Imprenta y reproducción",1),
			("4","03","07","03","Relaciones sociales",1),
			("4","03","07","04","Avisos",1),
			("4","03","08","01","Primas y gastos de seguros",1),
			("4","03","08","02","Comisiones y gastos bancarios",1),
			("4","03","08","03","Comisiones y gastos de adquisición de seguros",1),
			("4","03","09","01","Viáticos y pasajes dentro del país",1),
			("4","03","09","02","Viáticos y pasajes fuera del país",1),
			("4","03","09","03","Asignación por kilómetros recorridos",1),
			("4","03","10","01","Servicios jurídicos",1),
			("4","03","10","02","Servicios de contabilidad y auditoría",1),
			("4","03","10","03","Servicios de procesamiento de datos",1),
			("4","03","10","04","Servicios de ingeniería y arquitectónicos",1),
			("4","03","10","05","Servicios médicos, odontológicos y otros servicios de sanidad",1),
			("4","03","10","06","Servicios de veterinaria",1),
			("4","03","10","07","Servicios de capacitación y adiestramiento",1),
			("4","03","10","08","Servicios presupuestarios",1),
			("4","03","10","09","Servicios de lavandería y tintorería",1),
			("4","03","10","10","Servicios de vigilancia y seguridad",1),
			("4","03","10","11","Servicios para la elaboración y suministro de comida",1),
			("4","03","10","99","Otros servicios profesionales y técnicos",1),
			("4","03","11","01","Conservación y reparaciones menores de maquinaria y demás equipos de construcción, campo, industria y taller",1),
			("4","03","11","02","Conservación y reparaciones menores de equipos de transporte, tracción y elevación",1),
			("4","03","11","03","Conservación y reparaciones menores de equipos de comunicaciones y de señalamiento",1),
			("4","03","11","04","Conservación y reparaciones menores de equipos médicoquirúrgicos dentales y de veterinaria",1),
			("4","03","11","05","Conservación y reparaciones menores de equipos científicos, religiosos, de enseñanza y recreación",1),
			("4","03","11","06","Conservación y reparaciones menores de equipos y armamentos de orden público, seguridad y defensa nacional",1),
			("4","03","11","07","Conservación y reparaciones menores de máquinas, muebles y demás equipos de oficina y alojamiento",1),
			("4","03","11","99","Conservación y reparaciones menores de otras maquinaria y equipos",1),
			("4","03","12","01","Conservación y reparaciones menores de obras en bienes del dominio privado",1),
			("4","03","12","02","Conservación y reparaciones menores de obras en bienes del dominio público",1),
			("4","03","13","01","Servicios de construcciones temporales",1),
			("4","03","14","01","Servicios de construcción de edificaciones para la venta",1),
			("4","03","15","01","Derechos de importación y servicios aduaneros",1),
			("4","03","15","02","Tasas y otros derechos obligatorios",1),
			("4","03","15","03","Asignación a agentes de especies fiscales",1),
			("4","03","15","99","Otros servicios fiscales",1),
			("4","03","16","01","Servicios de diversión, esparcimiento y culturales",1),
			("4","03","17","01","Servicios de gestión administrativa prestados por organismos de asistencia técnica",1),
			("4","03","18","01","Impuesto al valor agregado",1),
			("4","03","18","99","Otros impuestos indirectos",1),
			("4","03","19","01","Comisiones por servicios para cumplir con los beneficios sociales",1),
			("4","03","99","01","Otros servicios no personales",1),
			("4","04","01","01","Repuestos mayores",1),
			("4","04","01","02","Reparaciones, mejoras y adiciones mayores de maquinaria y equipos",1),
			("4","04","02","01","Conservación, ampliaciones y mejoras mayores de obras en bienes del dominio privado",1),
			("4","04","02","02","Conservación, ampliaciones y mejoras mayores de obras en bienes del dominio público",1),
			("4","04","03","01","Maquinaria y demás equipos de construcción y mantenimiento",1),
			("4","04","03","02","Maquinaria y equipos para mantenimiento de automotores",1),
			("4","04","03","03","Maquinaria y equipos agrícolas y pecuarios",1),
			("4","04","03","04","Maquinaria y equipos de artes gráficas y reproducción",1),
			("4","04","03","05","Maquinaria y equipos industriales y de taller",1),
			("4","04","03","06","Maquinaria y equipos de energía",1),
			("4","04","03","07","Maquinaria y equipos de riego y acueductos",1),
			("4","04","03","08","Equipos de almacén",1),
			("4","04","03","99","Otra maquinaria y demás equipos de construcción, campo, industria y taller",1),
			("4","04","04","01","Vehículos automotores terrestres",1),
			("4","04","04","02","Equipos ferroviarios y de cables aéreos",1),
			("4","04","04","03","Equipos marítimos de transporte",1),
			("4","04","04","04","Equipos aéreos de transporte",1),
			("4","04","04","05","Vehículos de tracción no motorizados",1),
			("4","04","04","06","Equipos auxiliares de transporte",1),
			("4","04","04","99","Otros equipos de transporte, tracción y elevación",1),
			("4","04","05","01","Equipos de telecomunicaciones",1),
			("4","04","05","02","Equipos de señalamiento",1),
			("4","04","05","03","Equipos de control de tráfico aéreo",1),
			("4","04","05","04","Equipos de correo",1),
			("4","04","05","99","Otros equipos de comunicaciones y de señalamiento",1),
			("4","04","06","01","Equipos médico - quirúrgicos, dentales y de veterinaria",1),
			("4","04","06","99","Otros equipos médico - quirúrgicos, dentales y de veterinaria",1),
			("4","04","07","01","Equipos científicos y de laboratorio",1),
			("4","04","07","02","Equipos de enseñanza, deporte y recreación",1),
			("4","04","07","03","Obras de arte",1),
			("4","04","07","04","Libros, revistas y otros instrumentos de enseñanzas",1),
			("4","04","07","05","Equipos religiosos",1),
			("4","04","07","06","Instrumentos musicales y equipos de audio",1),
			("4","04","07","99","Otros equipos científicos, religiosos, de enseñanza y recreación",1),
			("4","04","08","01","Equipos y armamentos de orden público, seguridad y defensa nacional",1),
			("4","04","08","02","Equipos y armamentos de seguridad para la custodia y resguardo personal",1),
			("4","04","08","99","Otros equipos y armamentos de orden público, seguridad y defensa",1),
			("4","04","09","01","Mobiliario y equipos de oficina",1),
			("4","04","09","02","Equipos de computación",1),
			("4","04","09","03","Mobiliario y equipos de alojamiento",1),
			("4","04","09","99","Otras máquinas, muebles y demás equipos de oficina y alojamiento",1),
			("4","04","10","01","Semovientes",1),
			("4","04","11","01","Adquisición de tierras y terrenos",1),
			("4","04","11","02","Adquisición de edificios e instalaciones",1),
			("4","04","11","03","Expropiación de tierras y terrenos",1),
			("4","04","11","04","Expropiación de edificios e instalaciones",1),
			("4","04","11","05","Adquisición de maquinaria y equipos usados",1),
			("4","04","12","01","Marcas de fábrica y patentes de invención",1),
			("4","04","12","02","Derechos de autor",1),
			("4","04","12","03","Gastos de organización",1),
			("4","04","12","04","Paquetes y programas de computación",1),
			("4","04","12","05","Estudios y proyectos",1),
			("4","04","12","99","Otros activos intangibles",1),
			("4","04","13","01","Estudios y proyectos aplicables a bienes del dominio privado",1),
			("4","04","13","02","Estudios y proyectos aplicables a bienes del dominio público",1),
			("4","04","14","01","Contratación de inspección de obras de bienes del dominio privado",1),
			("4","04","14","02","Contratación de inspección de obras de bienes del dominio público",1),
			("4","04","15","01","Construcciones de edificaciones médico-asistenciales",1),
			("4","04","15","02","Construcciones de edificaciones militares y de seguridad",1),
			("4","04","15","03","Construcciones de edificaciones educativas, religiosas y recreativas",1),
			("4","04","15","04","Construcciones de edificaciones culturales y deportivas",1),
			("4","04","15","05","Construcciones de edificaciones para oficina",1),
			("4","04","15","06","Construcciones de edificaciones industriales",1),
			("4","04","15","07","Construcciones de edificaciones habitacionales",1),
			("4","04","15","99","Otras construcciones del dominio privado",1),
			("4","04","16","01","Construcción de vialidad",1),
			("4","04","16","02","Construcción de plazas, parques y similares",1),
			("4","04","16","03","Construcciones de instalaciones hidráulicas",1),
			("4","04","16","04","Construcciones de puertos y aeropuertos",1),
			("4","04","16","99","Otras construcciones del dominio público",1),
			("4","04","99","01","Otros activos reales",1),
			("4","05","01","01","Aportes en acciones y participaciones de capital al sector privado",1),
			("4","05","01","02","Aportes en acciones y participaciones de capital al sector público",1),
			("4","05","01","03","Aportes en acciones y participaciones de capital al sector externo",1),
			("4","05","02","01","Adquisición de títulos y valores a corto plazo",1),
			("4","05","02","02","Adquisición de títulos y valores a largo plazo",1),
			("4","05","03","01","Concesión de préstamos al sector público a corto plazo",1),
			("4","05","03","02","Concesión de préstamos al sector público a corto plazo",1),
			("4","05","03","03","Concesión de préstamos al sector externo a corto plazo",1),
			("4","05","04","01","Concesión de préstamos al sector privado a largo plazo",1),
			("4","05","04","02","Concesión de préstamos al sector público a largo plazo",1),
			("4","05","04","03","Concesión de préstamos al sector externo a largo plazo",1),
			("4","05","05","01","Incremento en caja",1),
			("4","05","05","02","Incremento en bancos",1),
			("4","05","05","03","Incremento de inversiones temporales",1),
			("4","05","06","01","Incremento de cuentas comerciales por cobrar a corto plazo",1),
			("4","05","06","02","Incremento de rentas por recaudar a corto plazo",1),
			("4","05","06","03","Incremento de deudas por rendir",1),
			("4","05","06","99","Incremento de otras cuentas por cobrar a corto plazo",1),
			("4","05","07","01","Incremento de efectos comerciales por cobrar a corto plazo",1),
			("4","05","07","99","Incremento de otros efectos por cobrar a corto plazo",1),
			("4","05","08","01","Incremento de cuentas comerciales por cobrar a mediano y largo plazo",1),
			("4","05","08","02","Incremento de rentas por recaudar a mediano y largo plazo",1),
			("4","05","08","99","Incremento de otras cuentas por cobrar a mediano y largo plazo",1),
			("4","05","09","01","Incremento de efectos comerciales por cobrar a mediano y largo plazo",1),
			("4","05","09","99","Incremento de otros efectos por cobrar a mediano y largo plazo",1),
			("4","05","10","01","Incremento de fondos en avance",1),
			("4","05","10","02","Incremento de fondos en anticipos",1),
			("4","05","10","03","Incremento de fondos en fideicomiso",1),
			("4","05","10","04","Incremento de anticipos a proveedores",1),
			("4","05","10","05","Incremento de anticipos a contratistas por contratos de corto plazo",1),
			("4","05","10","06","Incremento de anticipos a contratistas por contratos de mediano y largo plazo",1),
			("4","05","11","01","Incremento de gastos a corto plazo pagados por anticipado",1),
			("4","05","11","02","Incremento de depósitos otorgados en garantía a corto plazo",1),
			("4","05","11","99","Incremento de otros activos diferidos a corto plazo",1),
			("4","05","12","01","Incremento de gastos a mediano y largo plazo pagados por anticipado",1),
			("4","05","12","02","Incremento de depósitos otorgados en garantía a mediano y largo plazo",1),
			("4","05","12","99","Incremento de otros activos diferidos a mediano y largo plazo",1),
			("4","05","13","01","Incremento del Fondo de Estabilización Macroeconómica (FEM) de la República",1),
			("4","05","13","02","Incremento del Fondo de Estabilización Macroeconómica (FEM) del Poder Estadal",1),
			("4","05","13","03","Incremento del Fondo de Estabilización Macroeconómica (FEM) del Poder Municipal",1),
			("4","05","14","01","Incremento del Fondo de Ahorro Intergeneracional",1),
			("4","05","16","01","Incremento del Fondo de Aportes del Sector Público",1),
			("4","05","20","01","Incremento de otros activos financieros circulantes",1),
			("4","05","21","01","Incremento de activos en gestión judicial a mediano y largo plazo",1),
			("4","05","21","02","Incremento de títulos y otros valores de la deuda pública en litigio a largo plazo",1),
			("4","05","21","99","Incremento de otros activos financieros no circulantes",1),
			("4","05","99","01","Otros activos financieros",1),
			("4","06","01","01","Gastos de defensa y seguridad del Estado",1),
			("4","07","01","01","Transferencias corrientes internas al sector privado",1),
			("4","07","01","02","Donaciones corrientes internas al sector privado",1),
			("4","07","01","03","Transferencias corrientes internas al sector público",1),
			("4","07","01","04","Donaciones corrientes internas al sector público",1),
			("4","07","01","05","Pensiones de altos funcionarios y altas funcionarias del poder público y de elección popular, del personal de alto nivel y de dirección",1),
			("4","07","01","06","Jubilaciones de altos funcionarios y altas funcionarias del poder público y de elección popular, del personal de alto nivel y de dirección",1),
			("4","07","02","01","Transferencias corrientes al exterior",1),
			("4","07","02","02","Donaciones corrientes al exterior",1),
			("4","07","03","01","Transferencias de capital internas al sector privado",1),
			("4","07","03","02","Donaciones de capital internas al sector privado",1),
			("4","07","03","03","Transferencias de capital internas al sector público",1),
			("4","07","03","04","Donaciones de capital internas al sector público",1),
			("4","07","04","01","Transferencias de capital al exterior",1),
			("4","07","04","02","Donaciones de capital al exterior",1),
			("4","07","05","01","Situado Constitucional",1),
			("4","07","05","02","Situado Estadal a Municipal",1),
			("4","07","06","01","Subsidio de Régimen Especial",1),
			("4","07","07","01","Subsidio de capitalidad",1),
			("4","07","08","01","Asignaciones Económicas Especiales (LAEE) Estadal",1),
			("4","07","08","02","Asignaciones Económicas Especiales (LAEE) Estadal a Municipal",1),
			("4","07","08","03","Asignaciones Económicas Especiales (LAEE) Municipal",1),
			("4","07","08","04","Asignaciones Económicas Especiales (LAEE) Fondo Nacional de los Consejos Comunales",1),
			("4","07","08","05","Asignaciones Económicas Especiales (LAEE) Apoyo al Fortalecimiento Institucional",1),
			("4","07","09","01","Aportes al Poder Estadal por transferencia de servicios",1),
			("4","07","09","02","Aportes al Poder Municipal por transferencia de servicios",1),
			("4","07","10","01","Fondo Intergubernamental para la Descentralización (FIDES)",1),
			("4","07","11","01","Fondo de Compensación Interterritorial Estadal",1),
			("4","07","11","02","Fondo de Compensación Interterritorial Municipal",1),
			("4","07","11","03","Fondo de Compensación Interterritorial Poder Popular",1),
			("4","07","11","04","Fondo de Compensación Interterritorial Fortalecimiento Institucional",1),
			("4","07","12","01","Transferencias y donaciones corrientes a Consejos Comunales",1),
			("4","07","12","02","Transferencias y donaciones de capital a Consejos Comunales",1),
			("4","08","01","01","Depreciación",1),
			("4","08","01","02","Amortización",1),
			("4","08","02","01","Intereses por depósitos internos",1),
			("4","08","02","02","Intereses por títulos y valores",1),
			("4","08","02","03","Intereses por otros financiamientos",1),
			("4","08","03","01","Gastos de siniestros",1),
			("4","08","03","02","Gastos de operaciones de reaseguros",1),
			("4","08","03","99","Otros gastos de operaciones de seguro",1),
			("4","08","04","01","Pérdidas en el proceso de distribución de los servicios",1),
			("4","08","04","99","Otras pérdidas en operación",1),
			("4","08","05","01","Devoluciones de cobros indebidos",1),
			("4","08","05","02","Devoluciones y reintegros diversos",1),
			("4","08","05","03","Indemnizaciones diversas",1),
			("4","08","06","01","Pérdidas en inventarios",1),
			("4","08","06","02","Pérdidas en operaciones cambiarias",1),
			("4","08","06","03","Pérdidas en ventas de activos",1),
			("4","08","06","04","Pérdidas por cuentas incobrables",1),
			("4","08","06","05","Participación en pérdidas de otras empresas",1),
			("4","08","06","06","Pérdidas por auto-seguro",1),
			("4","08","06","07","Impuestos directos",1),
			("4","08","06","08","Intereses de mora",1),
			("4","08","06","09","Reservas técnicas",1),
			("4","08","07","01","Descuentos sobre ventas",1),
			("4","08","07","02","Bonificaciones por ventas",1),
			("4","08","07","03","Devoluciones por ventas",1),
			("4","08","07","04","Devoluciones por primas de seguro",1),
			("4","08","08","01","Indemnizaciones por daños y perjuicios",1),
			("4","08","08","02","Sanciones pecuniarias",1),
			("4","08","99","01","Otros gastos",1),
			("4","09","01","01","Asignaciones no distribuidas de la Asamblea Nacional",1),
			("4","09","02","01","Asignaciones no distribuidas de la Contraloría General de la República",1),
			("4","09","03","01","Asignaciones no distribuidas del Consejo Nacional Electoral",1),
			("4","09","04","01","Asignaciones no distribuidas del Tribunal Supremo de Justicia",1),
			("4","09","05","01","Asignaciones no distribuidas del Ministerio Público",1),
			("4","09","06","01","Asignaciones no distribuidas de la Defensoría del Pueblo",1),
			("4","09","07","01","Asignaciones no distribuidas del Consejo Moral Republicano",1),
			("4","09","08","01","Reestructuración de organismos del sector público",1),
			("4","09","09","01","Fondo de apoyo al trabajador y su grupo familiar de la Administración Pública Nacional",1),
			("4","09","09","02","Fondo de apoyo al trabajador y su grupo familiar de las Entidades Federales, los Municipios y otras formas de gobierno municipal",1),
			("4","09","10","01","Reforma de la seguridad social",1),
			("4","09","11","01","Emergencias en el territorio nacional",1),
			("4","09","12","01","Fondo para la cancelación de pasivos laborales",1),
			("4","09","13","01","Fondo para la cancelación de deuda por servicios de electricidad teléfono, aseo, agua y condominio, de los organismos de la Administración Central",1),
			("4","09","13","02","Fondo para la cancelación de deuda por servicios de electricidad teléfono, aseo, agua y condominio, de los organismos de la  Administración Descentralizada Nacional",1),
			("4","09","14","01","Fondo para remuneraciones, pensiones y jubilaciones y otras retribuciones",1),
			("4","09","15","01","Fondo para atender compromisos generados de la Ley Orgánica del Trabajo, los Trabajadores y las Trabajadoras",1),
			("4","09","16","01","Asignaciones para cancelar compromisos pendientes de ejercicios anteriores",1),
			("4","09","17","01","Asignaciones para cancelar la deuda Fogade – Ministerio competente en Materia de Finanzas – Banco Central de Venezuela (BCV)",1),
			("4","09","18","01","Asignaciones para atender los gastos de la referenda y elecciones",1),
			("4","09","19","01","Asignaciones para atender los gastos por honorarios profesionales de bufetes internacionales, costas y costos judiciales",1),
			("4","09","20","01","Fondo para atender compromisos generados por la contratación colectiva",1),
			("4","09","21","01","Proyecto social especial",1),
			("4","09","22","01","Asignaciones para programas y proyectos financiados con recursos de organismos multilaterales y/o bilaterales",1),
			("4","09","23","01","Asignación para facilitar la preparación de proyectos",1),
			("4","09","24","01","Programas de inversión para las entidades estadales municipalidades y otras instituciones",1),
			("4","09","25","01","Cancelación de compromisos",1),
			("4","09","26","01","Asignaciones para atender gastos de los organismos del sector público",1),
			("4","09","27","01","Convenio de Cooperación Especial",1),
			("4","10","01","01","Servicio de la deuda pública interna a corto plazo de títulos valores",1),
			("4","10","01","02","Servicio de la deuda pública interna por préstamos a corto plazo",1),
			("4","10","01","03","Servicio de la deuda pública interna indirecta por préstamos a corto plazo",1),
			("4","10","02","01","Servicio de la deuda pública interna a largo plazo de títulos y valores",1),
			("4","10","02","02","Servicio de la deuda pública interna por préstamos a largo plazo",1),
			("4","10","02","03","Servicio de la deuda pública interna indirecta a largo plazo de títulos y valores",1),
			("4","10","02","04","Servicio de la deuda pública interna indirecta por préstamos a largo plazo",1),
			("4","10","03","01","Servicio de la deuda pública externa a corto plazo de títulos y valores",1),
			("4","10","03","02","Servicio de la deuda pública externa por préstamos a corto plazo",1),
			("4","10","03","03","Servicio de la deuda pública externa indirecta por préstamos a corto plazo",1),
			("4","10","04","01","Servicio de la deuda pública externa a largo plazo de títulos y valores",1),
			("4","10","04","02","Servicio de la deuda pública externa por préstamos a largo plazo",1),
			("4","10","04","03","Servicio de la deuda pública externa indirecta a largo plazo de títulos y valores",1),
			("4","10","04","04","Servicio de la deuda pública externa indirecta por préstamos a largo plazo",1),
			("4","10","05","01","Disminución por reestructuración y/o refinanciamiento de la deuda interna a largo plazo, en a corto plazo",1),
			("4","10","05","02","Disminución por reestructuración y/o refinanciamiento de la deuda interna a corto plazo, en a largo plazo",1),
			("4","10","05","03","Disminución por reestructuración y/o refinanciamiento de la deuda externa a largo plazo, en a corto plazo",1),
			("4","10","05","04","Disminución por reestructuración y/o refinanciamiento de la deuda externa a corto plazo, en a largo plazo",1),
			("4","10","05","05","Disminución de la deuda pública por distribuir",1),
			("4","10","06","01","Amortización de la deuda pública de obligaciones pendientes de ejercicios anteriores",1),
			("4","10","06","02","Intereses de la deuda pública de obligaciones pendientes de ejercicios anteriores",1),
			("4","10","06","03","Intereses por mora y multas de la deuda pública de obligaciones pendientes de ejercicios anteriores",1),
			("4","10","06","04","Comisiones y otros gastos de la deuda pública de obligaciones pendientes de ejercicios anteriores",1),
			("4","11","01","01","Disminución de sueldos, salarios y otras remuneraciones por pagar",1),
			("4","11","02","01","Disminución de aportes patronales y retenciones laborales por pagar al Instituto Venezolano de los Seguros Sociales (IVSS)",1),
			("4","11","02","02","Disminución de aportes patronales y retenciones laborales por pagar al Instituto de Previsión Social del Ministerio de Educación (Ipasme)",1),
			("4","11","02","03","Disminución de aportes patronales y retenciones laborales por pagar al Fondo de Jubilaciones",1),
			("4","11","02","04","Disminución de aportes patronales y retenciones laborales por pagar al Fondo de Seguro de Paro Forzoso",1),
			("4","11","02","05","Disminución de aportes patronales y retenciones laborales por pagar al Fondo de Ahorro Obligatorio para la Vivienda (FAOV)",1),
			("4","11","02","06","Disminución de aportes patronales y retenciones laborales por pagar al seguro de vida, accidentes personales, hospitalización, cirugía, maternidad (HCM) y gastos funerarios",1),
			("4","11","02","07","Disminución de aportes patronales y retenciones laborales por pagar a cajas de ahorro",1),
			("4","11","02","08","Disminución de aportes patronales por pagar a organismos de seguridad social",1),
			("4","11","02","09","Disminución de retenciones laborales por pagar al Instituto Nacional de Capacitación y Educación Socialista (Inces)",1),
			("4","11","02","10","Disminución de retenciones laborales por pagar por pensión alimenticia",1),
			("4","11","02","98","Disminución de otros aportes legales por pagar",1),
			("4","11","02","99","Disminución de otras retenciones laborales por pagar",1),
			("4","11","03","01","Disminución de cuentas por pagar a proveedores a corto plazo",1),
			("4","11","03","02","Disminución de efectos por pagar a proveedores a corto plazo",1),
			("4","11","03","03","Disminución de cuentas por pagar a proveedores a mediano y largo plazo",1),
			("4","11","03","04","Disminución de efectos por pagar a proveedores a mediano y largo plazo",1),
			("4","11","04","01","Disminución de cuentas por pagar a contratistas a corto plazo",1),
			("4","11","04","02","Disminución de efectos por pagar a contratistas a corto plazo",1),
			("4","11","04","03","Disminución de cuentas por pagar a contratistas a mediano largo y plazo",1),
			("4","11","04","04","Disminución de efectos por pagar a contratistas a mediano y plazo",1),
			("4","11","05","01","Disminución de intereses internos por pagar",1),
			("4","11","05","02","Disminución de intereses externos por pagar",1),
			("4","11","06","01","Disminución de obligaciones de ejercicios anteriores",1),
			("4","11","06","02","Disminución de otras cuentas por pagar a corto plazo",1),
			("4","11","06","03","Disminución de otros efectos por pagar a corto plazo",1),
			("4","11","07","01","Disminución de pasivos diferidos a corto plazo",1),
			("4","11","07","02","Disminución de pasivos diferidos a mediano y largo plazo",1),
			("4","11","08","01","Disminución de provisiones",1),
			("4","11","08","02","Disminución de reservas técnicas",1),
			("4","11","09","01","Disminución de depósitos recibidos en garantía",1),
			("4","11","09","99","Disminución de otros fondos de terceros",1),
			("4","11","10","01","Disminución de depósitos a la vista",1),
			("4","11","10","02","Disminución de depósitos a plazo fijo",1),
			("4","11","11","01","Devoluciones de cobros indebidos",1),
			("4","11","11","02","Devoluciones y reintegros diversos",1),
			("4","11","11","03","Indemnizaciones diversas",1),
			("4","11","11","04","Compromisos pendientes de ejercicios anteriores",1),
			("4","11","11","05","Prestaciones sociales originadas por la aplicación de la Ley Orgánica del Trabajo, los Trabajadores y las Trabajadoras",1),
			("4","11","98","01","Disminución de otros pasivos a corto plazo",1),
			("4","11","99","01","Disminución de otros pasivos a mediano y largo plazo",1),
			("4","12","01","01","Disminución del capital fiscal e institucional",1),
			("4","12","01","02","Disminución de aportes por capitalizar",1),
			("4","12","01","03","Disminución de dividendos a distribuir",1),
			("4","12","02","01","Disminución de reservas",1),
			("4","12","03","01","Ajuste por inflación",1),
			("4","12","04","01","Disminución de resultados acumulados",1),
			("4","12","04","02","Disminución de resultados del ejercicio",1),
			("4","98","01","01","Rectificaciones al presupuesto",1)')
		->execute();

		if(is_int($resultado)) //Insertados
		{
			echo "\033[32m ".$resultado." registros insertados con éxito.\033[0m\n";
		}
		
	}
}